title: zarnibonehtay@gmail.com
description: Lainkd
template:
  repo: zarnibonehtay@gmail.com-template
  name: zarnibonehtay@gmail.com
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
